version: '3.6'

services:
  sst-local-db:
    image: postgres:11
    container_name: sst-local-db
    ports:
      - '5438:5432'
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: myapp
